<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerV7eK9x7\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerV7eK9x7/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerV7eK9x7.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerV7eK9x7\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerV7eK9x7\App_KernelDevDebugContainer([
    'container.build_hash' => 'V7eK9x7',
    'container.build_id' => '1c39dfc6',
    'container.build_time' => 1763135819,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerV7eK9x7');
